# Generated by Django 4.2.6 on 2023-11-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('tech', 'Tech'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
