# Generated by Django 4.2.6 on 2023-11-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='000-111-333', max_length=15, unique=True),
        ),
    ]
