# Generated by Django 4.2.6 on 2023-11-19 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), choices=[('admin', 'Admin'), ('tech', 'Tech'), ('customer', 'Customer')], default=list, size=None),
        ),
    ]
