# Generated by Django 4.2.6 on 2023-11-29 08:36

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(max_length=100000, null=True, upload_to=account.models.upload_to),
        ),
    ]
