# Generated by Django 4.2.6 on 2023-11-27 06:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_remove_item_postedby_remove_item_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='postedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postedBy', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
            preserve_default=False,
        ),
    ]
