# Generated by Django 4.2.6 on 2023-11-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_item_category_alter_item_postedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('100', 'Available'), ('101', 'Rented'), ('102', 'Sold')], default=100, max_length=100),
        ),
    ]
