# Generated by Django 4.2.6 on 2023-11-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_item_available_for_sell_item_rent_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rent_end_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rent_start_date',
        ),
    ]
