# Generated by Django 4.2.6 on 2023-11-29 07:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_remove_item_rent_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='item_images/'), size=None),
        ),
    ]
