# Generated by Django 4.2.6 on 2023-11-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['title']},
        ),
    ]
